#PATHs
if [ -d "$HOME/bin" ]; then
    export PATH="$PATH:/$HOME/bin"
fi
if [ -d "$HOME/.local/bin" ]; then
    export PATH="$PATH:/$HOME/.local/bin"
fi
if [ -d /usr/games ]; then
    export PATH="$PATH:/usr/games"
fi
if [ -d /opt/homebrew/bin ]; then
    export PATH="$PATH:/opt/homebrew/bin"
fi
if [ -d /opt/homebrew/opt/python@3.13/libexec/bin ]; then
    export PATH="$PATH:/opt/homebrew/opt/python@3.13/libexec/bin"
fi
if [ -d /opt/homebrew/opt/coreutils/libexec/gnubin ]; then
    export PATH="$PATH:/opt/homebrew/opt/coreutils/libexec/gnubin"
fi

# ZSH-specific environment variables
## oh-my-zsh
# Automatically update oh-my-zsh without asking
DISABLE_UPDATE_PROMPT=true
# Disable oh-my-zsh auto-update checks
DISABLE_AUTO_UPDATE=false
# How often to check for oh-my-zsh updates
UPDATE_ZSH_DAYS=30
# Disable cowsay on login by default. Override in .profile.local
# NO_ZSHRC_COWSAY=0
NO_ZSHRC_COWSAY=1

# Programs expected to be installed by tools
# These are the name on $PATH, not the package name
dependencies=(
    tree
    nvim
    ag
    node
    cowsay
    fortune
)

# Load dotfiles directory into DOTFILES_DIR
# Dotfiles directory should be in environment or ~/.dotfiles-dir
if [ -f "$HOME/.dotfiles-dir" ]; then
    source "$HOME/.dotfiles-dir"
fi
# echo "Dotfiles: $DOTFILES_DIR"
if [ -n "$DOTFILES_DIR" ] && [ -d "$DOTFILES_DIR" ]; then
    # Load dependencies
    ## oh-my-zsh
    if [ ! -f "$DOTFILES_DIR/dependencies/ohmyzsh/oh-my-zsh.sh" ]; then
        cd "$DOTFILES_DIR"
        git submodule update --init
        cd -
    fi
    export ZSH=$DOTFILES_DIR/dependencies/ohmyzsh
    ## Gruvbox colors
    [[ -f "$DOTFILES_DIR/dependencies/gruvbox/gruvbox_256palette.sh" ]] && source "$DOTFILES_DIR/dependencies/gruvbox/gruvbox_256palette.sh"
fi

# Custom functions
source "$HOME/.zsh_functions"
missing_dependencies=()
for dependency in "${dependencies[@]}"; do
    if [ $(program_installed $dependency) -eq 0 ]; then
        echo "Found missing dependency $dependency"
        # missing_dependencies+="$dependency"
    fi
done
# echo "Missing dependencies: $missing_dependencies"

# Z
# . $DOTFILES_DIR/z/z.sh

# Set name of the theme to load.
# # Look in ~/.oh-my-zsh/themes/
ZSH_THEME="agnoster"

# Base16 Shell
# BASE16_SHELL="$HOME/.config/base16-shell/base16-tomorrow.dark.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
# BASE16_SHELL="$HOME/.config/base16-shell/base16-ocean.dark.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
#
# # Uncomment the following line to use case-sensitive completion.
# # CASE_SENSITIVE="true"
#
# # Uncomment the following line to disable colors in ls.
# # DISABLE_LS_COLORS="true"
#
# # Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"
#
# # Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"
#
# # Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"
#
# # Uncomment the following line if you want to disable marking untracked files
# # under VCS as dirty. This makes repository status check for large repositories
# # much, much faster.
# # DISABLE_UNTRACKED_FILES_DIRTY="true"
#
# # Uncomment the following line if you want to change the command execution time
# # stamp shown in the history command output.
# # The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# # HIST_STAMPS="mm/dd/yyyy"
#
# # Would you like to use another custom folder than $ZSH/custom?
# # ZSH_CUSTOM=/path/to/new-custom-folder

# # zsh-syntax-highlighting must come last
plugins=(archlinux colorize command-not-found cp git github bower grunt npm macos)
# tmux
zmodload zsh/zpty

# Enable environment variables as CD directories
setopt cdablevars
# Enable correction for mistyped commands
unsetopt correctall
setopt appendhistory autocd extendedglob
unsetopt beep
# alias make='nocorrect make'
# alias git='nocorrect git'

# User profiles
source $HOME/.profile
# Define $POWERLINE_ROOT
if [ -f $HOME/.profile.local ]; then
    source $HOME/.profile.local
fi

if [ -d $ZSH ] && [ ! -z $ZSH ]; then
    source $ZSH/oh-my-zsh.sh
fi

# Italic support
if [ -f $HOME/.xterm-256color-italic.terminfo ]; then
    tic $HOME/.xterm-256color-italic.terminfo
fi
if [ -f $HOME/.screen-256color-italic.terminfo ]; then
    tic $HOME/.screen-256color-italic.terminfo
fi

# Use neovim where available
if type nvim > /dev/null 2>&1; then
    alias vim='nvim'
fi

# # Preferred editor for local and remote sessions
# # if [[ -n $SSH_CONNECTION ]]; then
export EDITOR='vim'
# export TERM=xterm-256color

# # Set personal aliases, overriding those provided by oh-my-zsh libs,
# # plugins, and themes. Aliases can be placed here, though oh-my-zsh
# # users are encouraged to define aliases within the ZSH_CUSTOM folder.
# # For a full list of active aliases, run `alias`.
# #
# # Example aliases
# # alias zshconfig="mate ~/.zshrc"
# # alias ohmyzsh="mate ~/.oh-my-zsh"
alias -s txt=vim
alias -s .c=vim
# Crontab
#alias crontab-e='vim ~/.crontab && crontab ~/.crontab'

bindkey -v

# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit

DEFAULT_USER="$USER"

# Syntax highlighting configuration
# ZSH_HIGHLIGHT_STYLES[path]='bold'
# ZSH_HIGHLIGHT_STYLES[path_prefix]=none
# ZSH_HIGHLIGHT_STYLES[path_approx]='fg=yellow'
# ZSH_HIGHLIGHT_STYLES[globbing]='fg=yellow'

# Source files
#typeset -ga sources
#sources+=$DOTFILES_DIR/shortcuts.txt

# Powerline plugin from distribution agnostic install directory
# pip install --user powerline-status &>/dev/null
## Assemble list of possible sources
sources=()
if [[ -a $POWERLINE_ROOT/bindings/zsh/powerline.zsh ]]; then
    # Prefer user-set powerline directory
    sources+=$POWERLINE_ROOT/bindings/zsh/powerline.zsh
fi
# If $POWERLINE_ROOT not set or set incorrectly, try default locations
python_roots=()
if [ -d $HOME/.local/lib/ ]; then
    for directory in $(echo $HOME/.local/lib/python*(N)); do
        python_roots+=$directory
    done
fi
if [ -d $HOME/.local/share/pipx/venvs/powerline-status/lib/ ]; then
    for directory in $(echo $HOME/.local/share/pipx/venvs/powerline-status/lib/python*(N)); do
        python_roots+=$directory
    done
fi
if [ -d $HOME/.local/pipx/venvs/powerline-status/lib/ ]; then
    for directory in $(echo $HOME/.local/pipx/venvs/powerline-status/lib/python*(N)); do
        python_roots+=$directory
    done
fi
if [ -d /usr/lib/ ]; then
    for directory in $(echo /usr/lib/python*(N)); do
        python_roots+=$directory
    done
fi
if [ -d /usr/local/lib/ ]; then
    # TODO: Make this not print warnings when the directory doesn't exit
    for directory in $(echo /usr/local/lib/python*(N)); do
        python_roots+=$directory
    done
fi
for directory in $python_roots; do
    #for directory in $(echo $template); do
    if [ -d "$directory" ]; then
        sources+="$directory"/site-packages/powerline/bindings/zsh/powerline.zsh
        sources+="$directory"/dist-packages/powerline/bindings/zsh/powerline.zsh
    fi
    # done
done
found=0
for file in $sources; do
    if [[ -a $file ]]; then
        # echo "Sourcing Powerline binding: $file"
        source $file
        found=1
        break
    fi
done
if [ $found -eq 0 ]; then
    echo "Powerline binding not found.\nPlease set \$POWERLINE_ROOT in .profile.local"
fi

# Check dotfiles version
if [ -n "$NO_GIT_CHECK" ] && [ ! "$NO_GIT_CHECK" -eq 1 ]; then
    # 5 second timeout to avoid delaying
    timeout -k 5 5s $(which zsh) -c 'source ~/.zsh_functions && check_dotfiles_version'
    dotfiles_version=$?
    if [[ $dotfiles_version = 1 ]]; then
        echo "Dotfiles repository not present at $DOTFILES_DIR"
    elif [[ $dotfiles_version = 2 ]]; then
        echo "Dotfiles repository at $DOTFILES_DIR is outdated"
    elif [[ $dotfiles_version = 3 ]]; then
        echo "Dotfiles repository at $DOTFILES_DIR is ahead of origin"
    elif [[ $dotfiles_version = 4 ]]; then
        echo "Dotfiles repository at $DOTFILES_DIR has diverged from origin"
    elif [[ $dotfiles_version = 5 ]]; then
        echo "Dotfiles repository not set in $HOME/.dotfiles-dir"
        echo "Please run ./install.sh in dotfiles repository and exit to create ~/.dotfiles-dir"
        echo "The following will not work until this is set:"
        echo "  - oh-my-zsh will not be started"
        echo "  - gruvbox color palette will not be loaded"
        echo ""
    fi
fi
if [[ $(program_installed neofetch) == 1 ]]; then
    if [ ! -n "$NO_NEOFETCH" ] || [ "$NO_NEOFETCH" -eq 1 ]; then 
    else
        neofetch
    fi
fi

# TMuxinator Completion
# source ~/bin/tmuxinator.zsh

# Dircolors
# eval $(dircolors ~/.dircolors)

# Keybindings
bindkey -M vicmd 'K' run-help
bindkey -M viins ',,' vi-cmd-mode
# bindkey -M viins 'K' run-help

# This binds Ctrl-O to ranger-cd:
#zle -N ranger-cd
#bindkey '^o' ranger-cd
#zle -N terminal-clock
#bindkey '^t' terminal-clock

#alias sl="sl -laF"

# Tool options
export SHELLCHECK_OPTS="-e SC2029 -e SC2155"

if [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 
fi

# pyenv-virtualenv (for managing virtualenvs for different python versions)
if [[ $(program_installed pyenv) == 1 ]]; then
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
    eval "$(pyenv init -)"
    # eval "$(pyenv virtualenv-init -)"
fi

# Local overrides
if [ -f $HOME/.zshrc_local ]; then
    source $HOME/.zshrc_local
fi

if [ -f ~/.fzf.zsh ]; then
    source ~/.fzf.zsh
fi

if [ -n "$NO_ZSHRC_COWSAY" ] && [ ! "$NO_ZSHRC_COWSAY" -eq 1 ]; then
    # Make a random (cow?) with a random face say something
    fortune -a | fmt -80 -s | cowthink -$(shuf -n 1 -e b d g p s t w y)  -f $(shuf -n 1 -e $(cowsay -l | tail -n +2)) -n
fi
