# Dotfiles directory should be in environment or 
if [ -f "$HOME/.dotfiles-dir" ]; then
    $DOTFILES_DIR=$(cat "$HOME/.dotfiles-dir")
fi
if [ -n "$DOTFILES_DIR" ] && [ -d "$DOTFILES_DIR" ]; then
    # Gruvbox colors
    # source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"
    [[ -f "$DOTFILES_DIR/dependencies/gruvbox/gruvbox_256palette.sh" ]] && source "$HOME/dotfiles/dependencies/gruvbox/gruvbox_256palette.sh"
    if [ ! -f "$DOTFILES_DIR/dependencies/ohmyzsh/oh-my-zsh.sh" ]; then
        cd "$DOTFILES_DIR"
        git submodule update --init
        cd -
    fi
    export ZSH=$DOTFILES_DIR/dependencies/ohmyzsh
fi

# Custom functions
source "$HOME/.zsh_functions"

# Path to your oh-my-zsh installation.
#export RUST_SRC_PATH=/usr/local/src/rust/src

# Z
# . $DOTFILES_DIR/z/z.sh
# Set name of the theme to load.
# # Look in ~/.oh-my-zsh/themes/
# # Optionally, if you set this to "random", it'll load a random theme each
# # time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"
# Base16 Shell
# BASE16_SHELL="$HOME/.config/base16-shell/base16-tomorrow.dark.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
# BASE16_SHELL="$HOME/.config/base16-shell/base16-ocean.dark.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
#
# # Uncomment the following line to use case-sensitive completion.
# # CASE_SENSITIVE="true"
#
# # Uncomment the following line to disable bi-weekly auto-update checks.
# # DISABLE_AUTO_UPDATE="true"
#
# # Uncomment the following line to change how often to auto-update (in days).
# # export UPDATE_ZSH_DAYS=13
#
# # Uncomment the following line to disable colors in ls.
# # DISABLE_LS_COLORS="true"
#
# # Uncomment the following line to disable auto-setting terminal title.
# # DISABLE_AUTO_TITLE="true"
#
# # Uncomment the following line to enable command auto-correction.
# # ENABLE_CORRECTION="true"
#
# # Uncomment the following line to display red dots whilst waiting for completion.
# # COMPLETION_WAITING_DOTS="true"
#
# # Uncomment the following line if you want to disable marking untracked files
# # under VCS as dirty. This makes repository status check for large repositories
# # much, much faster.
# # DISABLE_UNTRACKED_FILES_DIRTY="true"
#
# # Uncomment the following line if you want to change the command execution time
# # stamp shown in the history command output.
# # The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# # HIST_STAMPS="mm/dd/yyyy"
#
# # Would you like to use another custom folder than $ZSH/custom?
# # ZSH_CUSTOM=/path/to/new-custom-folder

# # zsh-syntax-highlighting must come last
plugins=(archlinux colorize command-not-found cp git github bower grunt npm macos)
# tmux
zmodload zsh/zpty

# # User configuration

# Enable environment variables as CD directories
setopt cdablevars
# Enable correction for mistyped commands
unsetopt correctall
# alias make='nocorrect make'
# alias git='nocorrect git'

#PATHs
export PATH="$PATH:/home/brad/.local/bin"
#export PATH=$HOME/bin:/usr/local/bin:$PATH
#export MANPATH="/usr/local/man:$MANPATH"
#PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"
# Add user cowpath to COWPATH
#COWPATH="$COWPATH:$DOTFILES_DIR/cowfiles"
# Make a random (cow?) with a random face say something
# fortune -a | fmt -80 -s | cowthink -$(shuf -n 1 -e b d g p s t w y)  -f $(shuf -n 1 -e $(cowsay -l | tail -n +2)) -n

# User profiles
source $HOME/.profile
# Define $POWERLINE_ROOT
if [ -f $HOME/.profile.local ]; then
    source $HOME/.profile.local
fi

source $ZSH/oh-my-zsh.sh

# Italic support
if [ -f $HOME/.xterm-256color-italic.terminfo ]; then
    tic $HOME/.xterm-256color-italic.terminfo
fi
if [ -f $HOME/.screen-256color-italic.terminfo ]; then
    tic $HOME/.screen-256color-italic.terminfo
fi

# Use neovim where available
if type nvim > /dev/null 2>&1; then
    alias vim='nvim'
fi

# # Preferred editor for local and remote sessions
# # if [[ -n $SSH_CONNECTION ]]; then
export EDITOR='vim'
# export TERM=xterm-256color

# # else
# #   export EDITOR='mvim'
# # fi
#
# # Compilation flags
# # export ARCHFLAGS="-arch x86_64"
#
# # ssh
# # export SSH_KEY_PATH="~/.ssh/dsa_id"
#
# # Set personal aliases, overriding those provided by oh-my-zsh libs,
# # plugins, and themes. Aliases can be placed here, though oh-my-zsh
# # users are encouraged to define aliases within the ZSH_CUSTOM folder.
# # For a full list of active aliases, run `alias`.
# #
# # Example aliases
# # alias zshconfig="mate ~/.zshrc"
# # alias ohmyzsh="mate ~/.oh-my-zsh"
alias -s txt=vim
alias -s .c=vim
# Crontab
#alias crontab-e='vim ~/.crontab && crontab ~/.crontab'

# Lines configured by zsh-newuser-install
setopt appendhistory autocd extendedglob
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

DEFAULT_USER=brad

# Syntax highlighting configuration
# ZSH_HIGHLIGHT_STYLES[path]='bold'
# ZSH_HIGHLIGHT_STYLES[path_prefix]=none
# ZSH_HIGHLIGHT_STYLES[path_approx]='fg=yellow'
# ZSH_HIGHLIGHT_STYLES[globbing]='fg=yellow'

# Source files
#typeset -ga sources
#sources+=$DOTFILES_DIR/shortcuts.txt

# Powerline plugin from distribution agnostic install directory
# pip install --user powerline-status &>/dev/null
sources=()
if [[ -a $POWERLINE_ROOT/bindings/zsh/powerline.zsh ]]; then
    # Prefer user-set powerline directory
    sources+=$POWERLINE_ROOT/bindings/zsh/powerline.zsh
fi
# If $POWERLINE_ROOT not set or set incorrectly, try default locations
python_roots=()
if [ -d $HOME/.local/lib/ ]; then
    for directory in $(echo $HOME/.local/lib/python*); do
        python_roots+=$directory
    done
fi
if [ -d $HOME/.local/share/pipx/venvs/powerline-status/lib/ ]; then
    for directory in $(echo $HOME/.local/share/pipx/venvs/powerline-status/lib/python*); do
        python_roots+=$directory
    done
fi
if [ -d /usr/lib/ ]; then
    for directory in $(echo /usr/lib/python*); do
        python_roots+=$directory
    done
fi
if [ -d /usr/local/lib/ ]; then
    for directory in $(echo /usr/local/lib/python*); do
        python_roots+=$directory
    done
fi
for directory in $python_roots; do
    #for directory in $(echo $template); do
    if [ -d "$directory" ]; then
        sources+="$directory"/site-packages/powerline/bindings/zsh/powerline.zsh
        sources+="$directory"/dist-packages/powerline/bindings/zsh/powerline.zsh
    fi
    # done
done
found=0
for file in $sources; do
    if [[ -a $file ]]; then
        # echo "Sourcing Powerline binding: $file"
        source $file
        found=1
        break
    fi
done
if [ $found -eq 0 ]; then
    echo "Powerline binding not found.\nPlease set \$POWERLINE_ROOT in .profile.local"
fi

# Check dotfiles version
check_dotfiles_version
dotfiles_version=$?
if [[ $dotfiles_version = 1 ]]; then
    echo "Dotfiles repository not present at $DOTFILES_DIR"
elif [[ $dotfiles_version = 2 ]]; then
    echo "Dotfiles repository at $DOTFILES_DIR is outdated"
elif [[ $dotfiles_version = 3 ]]; then
    echo "Dotfiles repository at $DOTFILES_DIR is ahead of origin"
elif [[ $dotfiles_version = 4 ]]; then
    echo "Dotfiles repository at $DOTFILES_DIR has diverged from origin"
fi

# TMuxinator Completion
# source ~/bin/tmuxinator.zsh

# Dircolors
# eval $(dircolors ~/.dircolors)

# Keybindings
bindkey -M vicmd 'K' run-help
bindkey -M viins ',,' vi-cmd-mode
# bindkey -M viins 'K' run-help

# This binds Ctrl-O to ranger-cd:
#zle -N ranger-cd
#bindkey '^o' ranger-cd
#zle -N terminal-clock
#bindkey '^t' terminal-clock

#alias sl="sl -laF"

# Tool options
export SHELLCHECK_OPTS="-e SC2029 -e SC2155"

# Local overrides
if [ -f $HOME/.zshrc_local ]; then
    source $HOME/.zshrc_local
fi

if [ -f ~/.fzf.zsh ]; then
    source ~/.fzf.zsh
fi

if [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 
fi

# pyenv-virtualenv (for managing virtualenvs for different python versions)
if [[ $(program_installed pyenv) == 1 ]]; then
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
    eval "$(pyenv init -)"
    # eval "$(pyenv virtualenv-init -)"
fi

# Created by `pipx` on 2025-06-16 02:20:13
export PATH="$PATH:/home/brad/.local/bin"
export PATH=$PATH:/home/brad/bin
